[server]
port = 8010
cors = ["localhost"]

[logger]
level = "info"
path = "./log/klog.log"

[media]
media_dir = "./uploads"
max_file_size_mb = 10 # 10MB

[database]
type = "sqlite"
url = "./db/klog.db"

[redis]
addr = ""
password = ""

[jwt]
secret = "ahsucjshzgsfshaysudkxhsuzksgdoqlschu"
expire_hour = 72

[scheduler]
enabled = true
cleanup_cron = "0 0 3 * * 0"  # 每周日凌晨3点执行清理任务